baseURL = 'https://kylehickman.net/'
defaultContentLanguage = "en"
languageCode = 'en-us'
title = 'kylehickman.net'
enableRobotsTXT = true

theme = 'gokarna'
pygmentsStyle = "nord"

[params]
  avatarURL = "https://github.com/kjhickman.png"
  avatarSize = "size-m"
  avatarAltText = "kjhickman's avatar"
  description = "My thoughts and explorations on software and technology"
  showPostsOnHomePage = "popular"
  numberPostsOnHomePage = 3
  footer = "Kyle Hickman"
  accentColor = "#00D907"
  displayReadingTime = true
  
  [[params.socialIcons]]
    name = "twitter"
    url = "https://bsky.app/profile/kylehickman.net"
  
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/kjhickman"

  [[params.socialIcons]]
    name = "email"
    url = "mailto:kyle@txhickman.com"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    pre = "<span data-feather='book'></span>"
    weight = 1

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    pre = "<span data-feather='tag'></span>"
    weight = 2
    
  [[menu.main]]
    identifier = "github"
    url = "https://github.com/kjhickman"
    pre = "<span data-feather='github'></span>"
    weight = 3
    [menu.main.params]
        newPage = true
